artifacts_root: artifacts

data_injections:
  root_dir: artifacts/data_injections
  source_URL: https://github.com/viv6267/End-to-End-Mlops/blob/main/data.zip
  local_data_file: artifacts/data_injections/new_data.zip
  unzip_dir: artifacts/data_injections
