artifacts_root: artifacts

data_injections:
  root_dir: artifacts/data_injections
  source_URL: https://github.com/viv6267/End-to-End-Mlops/blob/main/data.zip
  local_data_file: artifacts/data_injections/new_data.zip
  unzip_dir: artifacts/data_injections

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_injections/WineQT.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformations:
  root_dir: artifacts/data_transformations
  unzip_dir: artifacts/data_injections/WineQT.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformations/train.csv
  test_data_path: artifacts/data_transformations/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformations/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metrics_file_name: artifacts/model_evaluation/metrics.json